server:
  port: 9092
  shutdown: graceful
  netty:
    # tcp server connection timeout
    connection-timeout: 3s
    # tcp server connection timeout when no data is transmitted
    idle-timeout: 20s

spring:
  application:
    name: enrollment-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:15432/enrollment_service_db
    pool:
      # max timeout connection to the db 6/12
      max-create-connection-time: 2s
      initial-size: 16
      max-size: 200 # stress test bottleneck, isolated env
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:15432/enrollment_service_db
  kafka:
    bootstrap-servers: localhost:9097
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        schema.registry.url: http://localhost:8081
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual

eureka:
  client:
    service-url:
      defaultZone: ${external.discovery-service-url}
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true

kafkaprops:
  enrollment-dispatch-topic: v1.enrollments_dispatch
  nack-sleep-duration: 100ms

external:
  discovery-service-url: http://localhost:8761/eureka/
  course-service-url: "http://course-service"
  # endpoint to collect data about prices and courses
  course-info-path: "/v1/courses/course-info"
  # connection timeout for Course Service
  default-timeout: 2s
  # waitie till retry time for Course Service
  retry-backoff: 100ms
  # amount of tries to connect to Course Service: 5 in real, 1 for stress testing
  retry-count: 1
  # factor to minimize the possibility of a scenario where several instances of the Enrollment Service would simultaneously send retries to the Course Service
  retry-jitter: 0.75
  zipkin-endpoint: http://localhost:9411/api/v2/spans
  loki-url: http://localhost:3100/loki/api/v1/push

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: ${external.zipkin-endpoint}
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
    enable:
      jvm: true
      http:
        server: true
      netty: true # reactive apps
      reactor: true # reactive apps
      r2dbc: true # reactive apps
#     hikaricp: true # non-reactive apps
#     tomcat: true # non-reactive apps

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  submit-enrollment:
    summary: Create a new enrollment
    description: |
      Creates a new enrollment for the specified user. 
      Course names are passed in the request body. 
      If any course is missing in the Course Service, a 500 error is returned.
  get-enrollments:
    summary: Get a list of user enrollments
    description: Returns a list of user enrollments, sorted by the enrollment creation date.
  response:
    submitOk: Enrollment successfully created.
    submitBadRequest: Enrollment was not created due to an error in the request. See the error message for details.
    submitNotFound: Enrollment was not created because some of the courses are missing in the catalog.
    submitInternalError: Enrollment was not created due to a server error. See the error message for details.
    getOk: List of user enrollments successfully generated.
    getBadRequest: Failed to generate list of user enrollments due to invalid request parameters.
